port: 8080

server:
  port: ${port}


jpa:
  hibernate:
    ddl-auto: validate
  show-sql: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ocg
    username: ocg
    password: ocg
    hikari:
      auto-commit: false


flyway-migrations:
  migrations:
    - schema: public
      location: classpath:db/migration
      baseline-on-migrate: false
      clean: true
      runDefaultCallbacks: true
